version: "3"
services:
  ghsci:
    image: globalhealthyliveablecities/global-indicators:v4.2.0
    container_name: ghsci
    shm_size: 2g
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["/bin/bash", "-c", 'sleep 3 && echo -e "$INSTRUCTIONS" && echo $"alias configure=\"python configure.py\"" >> ~/.bashrc && echo $"alias analysis=\"python analysis.py\"" >> ~/.bashrc && echo $"alias generate=\"python generate.py\"" >> ~/.bashrc && echo $"alias compare=\"python compare.py\"" >> ~/.bashrc  && /bin/bash']
    working_dir: /home/ghsci/work/process
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/ghsci/work
    user: "${UID}:${GID}"
    extra_hosts:
      - "gateway.docker.internal:host-gateway"
    environment:
        - configure
        - analysis
        - analyse
        - analyze
        - generate
        - compare
        - dollar
        - INSTRUCTIONS
        - help

  pgrouting:
    image: pgrouting/pgrouting
    container_name: ghscic_postgis
    command: postgres -c port=5433
    restart: unless-stopped
    ports:
      - "5433:5433"
    volumes:
      - db-data:/var/lib/postgis:/postgresql/13/main
    environment:
      POSTGRES_PASSWORD: ghscic
      POSTGRES_HOST: ghscic_postgis

volumes:
  db-data:
