name: Test
on:
  pull_request: { branches: main }
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull and launch GHSCI software and database
      run: sudo docker compose -f docker-compose.yml up -d 

    - name: echo working directory
      run: sudo docker compose exec -T ghsci echo ${pwd}

    - name: run analysis  
      run: sudo docker compose exec -T ghsci python /home/ghsci/process/analysis.py example_ES_Las_Palmas_2023
